#!/usr/bin/env python3
"""Render the homepage app list and the README table from the signed repo index.

Everything the page says about an app - version, size, licence, summary, icon,
download link - is in repo/index-v2.json, which `fdroid update` regenerates on
every publish. Typing it a second time by hand is what let the page drift two
releases behind the repo.
"""

import argparse
import base64
import html
import io
import json
import pathlib
import re
import sys
from typing import NamedTuple

ROOT = pathlib.Path(__file__).resolve().parent.parent
INDEX = ROOT / "repo" / "index-v2.json"
TEMPLATE = ROOT / "site" / "index.template.html"
PAGE = ROOT / "site" / "index.html"
README = ROOT / "README.md"

BEGIN = "<!-- apps:begin -->"
END = "<!-- apps:end -->"
BANNER = (
    "<!-- Generated by site/render.py from repo/index-v2.json."
    " Edit site/index.template.html, never this file. -->"
)

# An arm64-v8a phone is what everything shipped here runs on. The ABI split
# scheme puts x86_64 at the highest versionCode, so "newest" is the wrong pick.
ABI = "arm64-v8a"

MIB = 1024 * 1024

# The tile shows the icon in a 52 px box. The metadata icon behind it is up
# to 512 px, which nobody sees and everybody downloads.
ICON_PX = 144


class MarkerError(Exception):
    pass


class App(NamedTuple):
    package: str
    name: str
    summary: str
    license: str
    source: str
    version_name: str
    version_code: int
    apk_path: str
    apk_size: int
    icon_path: str
    prerelease: bool

    @property
    def size_label(self) -> str:
        return "%d MiB" % round(self.apk_size / MIB)

    @property
    def source_label(self) -> str:
        return "/".join(self.source.rstrip("/").split("/")[-2:])


def pick_apk(versions):
    fitting = [
        v
        for v in versions
        if ABI in (v["manifest"].get("nativecode") or [ABI])
    ]
    if not fitting:
        return None
    return max(fitting, key=lambda v: v["manifest"]["versionCode"])


def _localised(value):
    if not isinstance(value, dict):
        return value or ""
    return value.get("en-US") or next(iter(value.values()), "")


def load_apps(index):
    apps = []
    packages = sorted(
        index["packages"].items(), key=lambda kv: kv[1]["metadata"].get("added", 0)
    )
    for package, entry in packages:
        version = pick_apk(entry["versions"].values())
        if version is None:
            continue
        meta = entry["metadata"]
        version_name = version["manifest"]["versionName"]
        icon = _localised(meta.get("icon")) or {}
        apps.append(
            App(
                package=package,
                name=_localised(meta.get("name")) or package,
                summary=_localised(meta.get("summary")),
                license=meta.get("license", ""),
                source=meta.get("sourceCode") or meta.get("webSite", ""),
                version_name=version_name,
                version_code=version["manifest"]["versionCode"],
                apk_path=version["file"]["name"],
                apk_size=version["file"]["size"],
                icon_path=icon.get("name", ""),
                prerelease=version_name.split(".")[0] == "0",
            )
        )
    return apps


def scaled_png(source):
    raw = source.read_bytes()
    try:
        from PIL import Image
    except ImportError:
        return raw
    with Image.open(io.BytesIO(raw)) as image:
        if max(image.size) <= ICON_PX:
            return raw
        image = image.convert("RGBA")
        image.thumbnail((ICON_PX, ICON_PX), Image.LANCZOS)
        buffer = io.BytesIO()
        image.save(buffer, "PNG", optimize=True)
    return buffer.getvalue() if len(buffer.getvalue()) < len(raw) else raw


def data_uri_icon(app):
    source = ROOT / "repo" / app.icon_path.lstrip("/")
    if not source.is_file():
        return "/fdroid/repo" + app.icon_path
    encoded = base64.b64encode(scaled_png(source)).decode("ascii")
    return "data:image/png;base64," + encoded


PHONE_SVG = (
    '<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">'
    '<rect x="5" y="2.2" width="14" height="19.6" rx="2.6" fill="none"'
    ' stroke="currentColor" stroke-width="1.6"/>'
    '<path d="M12 7.4v6.4m0 0 2.5-2.5M12 13.8l-2.5-2.5" fill="none"'
    ' stroke="currentColor" stroke-width="1.6" stroke-linecap="round"'
    ' stroke-linejoin="round"/></svg>'
)

TRAY_SVG = (
    '<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">'
    '<path d="M12 3v10m0 0 3.3-3.3M12 13 8.7 9.7M4.6 15.4v3a2 2 0 0 0 2 2h10.8'
    'a2 2 0 0 0 2-2v-3" fill="none" stroke="currentColor" stroke-width="1.7"'
    ' stroke-linecap="round" stroke-linejoin="round"/></svg>'
)

TILE = """    <article class="app" data-pkg="{package}">
      <img src="{icon}" alt="{name} icon" width="52" height="52">
      <div class="body">
        <div class="row1">
          <a class="name" href="{source}">{name}</a>
          <span class="chip">v{version}</span>
        </div>
        <p class="sum">{summary}</p>
        <div class="meta">{license} · {package} · <a href="{source}">source ↗</a></div>
        <div class="get">
          <a class="badge" href="{repo_link}" aria-label="Get {name} on F-Droid: adds this repository to your client">
            {phone}<span class="t"><small>Get it on</small><b>F-Droid</b></span>
          </a>
          <a class="apk" href="/fdroid/repo{apk}" aria-label="Download the {name} APK for arm64-v8a, {size}">
            {tray}<span>APK <span class="size">{size}</span></span>
          </a>
        </div>
      </div>
    </article>"""


def render_tiles(apps, repo_link, icon_src):
    tiles = []
    for app in apps:
        summary = html.escape(app.summary)
        if summary and not summary.endswith("."):
            summary += "."
        tiles.append(
            TILE.format(
                package=html.escape(app.package, quote=True),
                icon=html.escape(icon_src(app), quote=True),
                name=html.escape(app.name),
                source=html.escape(app.source, quote=True),
                version=html.escape(app.version_name),
                summary=summary,
                license=html.escape(app.license),
                repo_link=html.escape(repo_link, quote=True),
                apk=html.escape(app.apk_path, quote=True),
                size=app.size_label,
                phone=PHONE_SVG,
                tray=TRAY_SVG,
            )
        )
    return "\n".join(tiles)


def render_table(apps):
    rows = []
    for app in apps:
        version = app.version_name + (" (pre-release)" if app.prerelease else "")
        rows.append(
            "| **%s** | %s | %s | %s | [%s](%s) |"
            % (app.name, app.summary, version, app.license, app.source_label, app.source)
        )
    return "\n".join(rows)


def replace_region(text, body):
    if BEGIN not in text or END not in text:
        raise MarkerError("missing %s / %s markers" % (BEGIN, END))
    pattern = re.compile(
        re.escape(BEGIN) + ".*?" + re.escape(END), re.DOTALL
    )
    return pattern.sub(lambda _: BEGIN + "\n" + body + "\n" + END, text, count=1)


def repo_link_of(template):
    match = re.search(r'fdroidrepos://[^"\s]+', template)
    if not match:
        raise MarkerError("no fdroidrepos:// link in the template")
    return match.group(0)


def render_all():
    index = json.loads(INDEX.read_text())
    apps = load_apps(index)
    template = TEMPLATE.read_text()
    page = replace_region(
        template, render_tiles(apps, repo_link_of(template), data_uri_icon)
    )
    page = page.replace("<!doctype html>", "<!doctype html>\n" + BANNER, 1)
    readme = replace_region(README.read_text(), render_table(apps))
    return apps, page, readme


def main(argv=None):
    args = argparse.ArgumentParser(description=__doc__).parse_args(argv)
    del args
    apps, page, readme = render_all()
    for path, text in ((PAGE, page), (README, readme)):
        before = path.read_text() if path.exists() else None
        path.write_text(text)
        print("%s %s" % ("unchanged" if text == before else "written  ", path.name))
    for app in apps:
        print("  %-24s v%-8s %s (%s)" % (app.package, app.version_name,
                                         app.apk_path.lstrip("/"), app.size_label))
    return 0


if __name__ == "__main__":
    sys.exit(main())
